### ISSUE TITLE
stringipc

### ISSUE THREAD

**Issue by Q4n** [ret2p4nda/kernel-pwn#1]
师傅你好, 我这在运行stringipc的start.sh脚本时, bash直接卡死. 无法正常启动

**Comment by Q4n** [comment]
环境ubuntu16.04.1

**Comment by ret2p4nda** [comment]
> 环境ubuntu16.04.1

抱歉 才看见这个issue， 需要gdb.sh一同启动，否则会停等。

**Comment by Q4n** [comment]
非常感谢师傅的回答~

**Comment by Q4n** [comment]
> > 环境ubuntu16.04.1
> 
> 抱歉 才看见这个issue， 需要gdb.sh一同启动，否则会停等。

感谢师傅的回答~
